server:
  port: 8082
logging:
  file:
    name: D://logs/globle.log
  level:
    com:
      shaohao:
        mytask:
          mapper: debug
task:
  poxy:
    hostname:  #hostname
    port: 10801
    userName: 98984
    passWord: 35133
  game:
    token:  Dc0MGY2MGRiNTE2OGU

  http:
    # newcall重试次数
    maxRetryCount: 3
    # 预期状态码
    expectedStatusCode: 0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: #jdbc:mysql://116.62.50.140
    username: root
    password:  # password
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      oracle-pooled-prepared-statements: false
      pool:
        prepared-statement-cache-enabled: false
        prepared-statement-cache-query-size: 0

  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai

mybatis:
  type-aliases-package: com.shaohao.mytask.entity
  mapper-locations:  classpath:mapper/*.xml
